import type { EntityDefinition } from "../types.js";
import {
  str, uuid, date, datetime, decimal, int32, bool, opt, ro,
} from "../helpers.js";

const listOnly = { list: true, create: false, modify: false, delete: false };

export const items: EntityDefinition = {
  entityName: "item",
  entitySetName: "items",
  pageId: "PAG30008",
  apiBase: "standard",
  description:
    "Exposes item master data including product descriptions, pricing, unit costs, tax groups, categorization, and real-time inventory levels. Supports full CRUD operations for creating, updating, retrieving, and deleting items, enabling seamless synchronization of product catalogs and inventory between Business Central and external e-commerce, warehouse, or retail systems.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("displayName", "Display Name"),
    str("displayName2", "Display Name 2"),
    opt("type", "Type", ["Inventory", "Service", "Non_x002D_Inventory"]),
    uuid("itemCategoryId", "Item Category Id"),
    str("itemCategoryCode", "Item Category Code"),
    bool("blocked", "Blocked"),
    str("gtin", "GTIN"),
    decimal("unitPrice", "Unit Price"),
    bool("priceIncludesTax", "Price Includes Tax"),
    decimal("unitCost", "Unit Cost"),
    uuid("taxGroupId", "Tax Group Id"),
    str("taxGroupCode", "Tax Group Code"),
    uuid("baseUnitOfMeasureId", "Base Unit of Measure Id"),
    str("baseUnitOfMeasureCode", "Base Unit of Measure Code"),
    uuid("generalProductPostingGroupId", "General Product Posting Group Id"),
    str("generalProductPostingGroupCode", "General Product Posting Group Code"),
    uuid("inventoryPostingGroupId", "Inventory Posting Group Id"),
    str("inventoryPostingGroupCode", "Inventory Posting Group Code"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
    ro(decimal("inventory", "Inventory")),
  ],
};

export const itemCategories: EntityDefinition = {
  entityName: "itemCategory",
  entitySetName: "itemCategories",
  pageId: "PAG30025",
  apiBase: "standard",
  description: "Exposes item category master data for product classification.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("displayName", "Display Name"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const itemVariants: EntityDefinition = {
  entityName: "itemVariant",
  entitySetName: "itemVariants",
  pageId: "PAG30052",
  apiBase: "standard",
  description: "Exposes item variant data linked to a parent item.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "items",
    parentKeyParam: "Item_id",
    parentDescription: "Parent item identification.",
    parentListTool: "ListItems_PAG30008",
  },
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("description", "Description"),
  ],
};

export const inventoryPostingGroups: EntityDefinition = {
  entityName: "inventoryPostingGroup",
  entitySetName: "inventoryPostingGroups",
  pageId: "PAG30096",
  apiBase: "standard",
  description: "Exposes inventory posting group setup data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("description", "Description"),
  ],
};

export const generalProductPostingGroups: EntityDefinition = {
  entityName: "generalProductPostingGroup",
  entitySetName: "generalProductPostingGroups",
  pageId: "PAG30079",
  apiBase: "standard",
  description: "Exposes general product posting group setup data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("description", "Description"),
  ],
};

export const unitsOfMeasure: EntityDefinition = {
  entityName: "unitOfMeasure",
  entitySetName: "unitsOfMeasure",
  pageId: "PAG30030",
  apiBase: "standard",
  description: "Exposes unit of measure definitions used across items and transactions.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("displayName", "Display Name"),
    str("internationalStandardCode", "International Standard Code"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const customers: EntityDefinition = {
  entityName: "customer",
  entitySetName: "customers",
  pageId: "PAG30009",
  apiBase: "standard",
  description:
    "Exposes customer master data including names, addresses, contact info, credit limits, payment terms, and tax settings. Enables synchronization of customer records between Business Central and external CRM, e-commerce, and invoicing systems.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("displayName", "Display Name"),
    str("type", "Type"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("email", "Email"),
    str("website", "Website"),
    str("taxLiable", "Tax Liable"),
    uuid("taxAreaId", "Tax Area Id"),
    str("taxAreaDisplayName", "Tax Area Display Name"),
    str("taxRegistrationNumber", "Tax Registration Number"),
    str("currencyId", "Currency Id"),
    str("currencyCode", "Currency Code"),
    uuid("paymentTermsId", "Payment Terms Id"),
    uuid("shipmentMethodId", "Shipment Method Id"),
    uuid("paymentMethodId", "Payment Method Id"),
    bool("blocked", "Blocked"),
    ro(decimal("balance", "Balance")),
    ro(decimal("overdueAmount", "Overdue Amount")),
    ro(decimal("totalSalesExcludingTax", "Total Sales Excluding Tax")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const customerFinancialDetails: EntityDefinition = {
  entityName: "customerFinancialDetail",
  entitySetName: "customerFinancialDetails",
  pageId: "PAG30048",
  apiBase: "standard",
  description: "Exposes customer financial details including balances, overdue amounts, and total sales.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("name", "Name"),
    decimal("balance", "Balance"),
    decimal("totalSalesExcludingTax", "Total Sales Excluding Tax"),
    decimal("overdueAmount", "Overdue Amount"),
  ],
};

export const customerContacts: EntityDefinition = {
  entityName: "customerContact",
  entitySetName: "customerContacts",
  pageId: "PAG30089",
  apiBase: "standard",
  description: "Exposes customer-linked contact records.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("customerNumber", "Customer Number"),
    str("customerName", "Customer Name"),
    str("contactName", "Contact Name"),
    str("contactNumber", "Contact Number"),
    str("contactType", "Contact Type"),
  ],
};

export const vendors: EntityDefinition = {
  entityName: "vendor",
  entitySetName: "vendors",
  pageId: "PAG30010",
  apiBase: "standard",
  description:
    "Exposes vendor master data including names, addresses, contact info, payment terms, currency, and tax settings.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("displayName", "Display Name"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("email", "Email"),
    str("website", "Website"),
    str("taxRegistrationNumber", "Tax Registration Number"),
    str("currencyId", "Currency Id"),
    str("currencyCode", "Currency Code"),
    uuid("paymentTermsId", "Payment Terms Id"),
    uuid("paymentMethodId", "Payment Method Id"),
    bool("taxLiable", "Tax Liable"),
    bool("blocked", "Blocked"),
    ro(decimal("balance", "Balance")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const contacts: EntityDefinition = {
  entityName: "contact",
  entitySetName: "contacts",
  pageId: "PAG30071",
  apiBase: "standard",
  description: "Exposes contact records for people and companies.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("type", "Type"),
    str("displayName", "Display Name"),
    str("companyName", "Company Name"),
    str("companyNumber", "Company Number"),
    str("businessRelation", "Business Relation"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("mobilePhoneNumber", "Mobile Phone Number"),
    str("email", "Email"),
    str("website", "Website"),
    str("searchName", "Search Name"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const contactsInformation: EntityDefinition = {
  entityName: "contactInformation",
  entitySetName: "contactsInformation",
  pageId: "PAG30072",
  apiBase: "standard",
  description: "Exposes extended contact information records.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("name", "Name"),
    str("type", "Type"),
    str("email", "Email"),
    str("phoneNumber", "Phone Number"),
    str("companyName", "Company Name"),
  ],
};

export const employees: EntityDefinition = {
  entityName: "employee",
  entitySetName: "employees",
  pageId: "PAG30017",
  apiBase: "standard",
  description: "Exposes employee records including personal details, employment dates, and status.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("displayName", "Display Name"),
    str("givenName", "Given Name"),
    str("middleName", "Middle Name"),
    str("surname", "Surname"),
    str("jobTitle", "Job Title"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("mobilePhone", "Mobile Phone"),
    str("email", "Email"),
    str("personalEmail", "Personal Email"),
    date("employmentDate", "Employment Date"),
    str("status", "Status"),
    date("birthDate", "Birth Date"),
    str("statisticsGroupCode", "Statistics Group Code"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const companyInformation: EntityDefinition = {
  entityName: "companyInformation",
  entitySetName: "companyInformation",
  pageId: "PAG30011",
  apiBase: "standard",
  description: "Exposes company-level information including name, address, tax registration, and communication details.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("displayName", "Display Name"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("faxNumber", "Fax Number"),
    str("email", "Email"),
    str("website", "Website"),
    str("taxRegistrationNumber", "Tax Registration Number"),
    str("currencyCode", "Currency Code"),
    str("industry", "Industry"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const countriesRegions: EntityDefinition = {
  entityName: "countryRegion",
  entitySetName: "countriesRegions",
  pageId: "PAG30027",
  apiBase: "standard",
  description: "Exposes country/region code and name definitions.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("displayName", "Display Name"),
    str("addressFormat", "Address Format"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const locations: EntityDefinition = {
  entityName: "location",
  entitySetName: "locations",
  pageId: "PAG30076",
  apiBase: "standard",
  description: "Exposes warehouse/location master data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("displayName", "Display Name"),
    str("contact", "Contact"),
    str("addressLine1", "Address Line 1"),
    str("addressLine2", "Address Line 2"),
    str("city", "City"),
    str("state", "State"),
    str("country", "Country/Region Code"),
    str("postalCode", "Postal Code"),
    str("phoneNumber", "Phone Number"),
    str("email", "Email"),
    str("website", "Website"),
  ],
};

export const salespersonsPurchasers: EntityDefinition = {
  entityName: "salespersonPurchaser",
  entitySetName: "salespersonsPurchasers",
  pageId: "PAG30075",
  apiBase: "standard",
  description: "Exposes salesperson and purchaser records.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("displayName", "Display Name"),
    str("email", "Email"),
    str("phoneNumber", "Phone Number"),
  ],
};

export const customerReturnReasons: EntityDefinition = {
  entityName: "customerReturnReason",
  entitySetName: "customerReturnReasons",
  pageId: "PAG30077",
  apiBase: "standard",
  description: "Exposes customer return reason codes.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("description", "Description"),
  ],
};

export const disputeStatus: EntityDefinition = {
  entityName: "disputeStatus",
  entitySetName: "disputeStatus",
  pageId: "PAG30088",
  apiBase: "standard",
  description: "Exposes dispute status records.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("code", "Code"),
    str("description", "Description"),
  ],
};

export const pictures: EntityDefinition = {
  entityName: "picture",
  entitySetName: "pictures",
  pageId: "PAG30053",
  apiBase: "standard",
  description: "Exposes picture attachments linked to parent entities (items, customers, vendors, employees).",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "items",
    parentKeyParam: "parent_id",
    parentDescription: "Parent entity id.",
    parentListTool: "ListItems_PAG30008",
  },
  properties: [
    uuid("id", "Id"),
    str("contentType", "Content Type"),
    int32("width", "Width"),
    int32("height", "Height"),
  ],
};

export const defaultDimensions: EntityDefinition = {
  entityName: "defaultDimension",
  entitySetName: "defaultDimensions",
  pageId: "PAG30054",
  apiBase: "standard",
  description: "Exposes default dimension settings linked to parent entities.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "customers",
    parentKeyParam: "parent_id",
    parentDescription: "Parent entity id.",
    parentListTool: "ListCustomers_PAG30009",
  },
  properties: [
    uuid("id", "Id"),
    uuid("parentId", "Parent Id"),
    str("dimensionId", "Dimension Id"),
    str("dimensionCode", "Dimension Code"),
    str("dimensionValueId", "Dimension Value Id"),
    str("dimensionValueCode", "Dimension Value Code"),
    str("postingValidation", "Posting Validation"),
  ],
};

export const documentAttachments: EntityDefinition = {
  entityName: "documentAttachment",
  entitySetName: "documentAttachments",
  pageId: "PAG30080",
  apiBase: "standard",
  description: "Exposes document attachments linked to parent entities.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "salesOrders",
    parentKeyParam: "parent_id",
    parentDescription: "Parent entity id.",
    parentListTool: "ListSalesOrders_PAG30028",
  },
  properties: [
    uuid("id", "Id"),
    str("fileName", "File Name"),
    str("byteSize", "Byte Size"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const attachments: EntityDefinition = {
  entityName: "attachment",
  entitySetName: "attachments",
  pageId: "PAG30039",
  apiBase: "standard",
  description: "Exposes file attachments linked to parent entities.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "salesInvoices",
    parentKeyParam: "parent_id",
    parentDescription: "Parent entity id.",
    parentListTool: "ListSalesInvoices_PAG30012",
  },
  properties: [
    uuid("id", "Id"),
    str("fileName", "File Name"),
    int32("byteSize", "Byte Size"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const masterDataEntities: EntityDefinition[] = [
  items,
  itemCategories,
  itemVariants,
  inventoryPostingGroups,
  generalProductPostingGroups,
  unitsOfMeasure,
  customers,
  customerFinancialDetails,
  customerContacts,
  vendors,
  contacts,
  contactsInformation,
  employees,
  companyInformation,
  countriesRegions,
  locations,
  salespersonsPurchasers,
  customerReturnReasons,
  disputeStatus,
  pictures,
  defaultDimensions,
  documentAttachments,
  attachments,
];
