import type { EntityDefinition } from "../types.js";
import {
  str, uuid, date, datetime, decimal, int32, bool, opt, ro,
} from "../helpers.js";

const listOnly = { list: true, create: false, modify: false, delete: false };

const purchaseLineProps = [
  uuid("id", "Id"),
  ro(uuid("documentId", "Document Id")),
  ro(int32("sequence", "Sequence")),
  uuid("itemId", "Item Id"),
  uuid("accountId", "Account Id"),
  opt("lineType", "Line Type", [
    "Comment",
    "Account",
    "Item",
    "Resource",
    "Fixed_x0020_Asset",
    "Charge",
  ]),
  str("lineObjectNumber", "Line Object Number"),
  str("description", "Description"),
  str("description2", "Description 2"),
  uuid("unitOfMeasureId", "Unit of Measure Id"),
  str("unitOfMeasureCode", "Unit of Measure Code"),
  decimal("quantity", "Quantity"),
  decimal("directUnitCost", "Direct Unit Cost"),
  decimal("discountAmount", "Discount Amount"),
  decimal("discountPercent", "Discount Percent"),
  ro(decimal("amountExcludingTax", "Amount Excluding Tax")),
  str("taxCode", "Tax Code"),
  ro(decimal("taxPercent", "Tax Percent")),
  ro(decimal("totalTaxAmount", "Total Tax Amount")),
  ro(decimal("amountIncludingTax", "Amount Including Tax")),
  ro(decimal("invoiceDiscountAllocation", "Invoice Discount Allocation")),
  ro(decimal("netAmount", "Net Amount")),
  ro(decimal("netTaxAmount", "Net Tax Amount")),
  ro(decimal("netAmountIncludingTax", "Net Amount Including Tax")),
  date("expectedReceiptDate", "Expected Receipt Date"),
  uuid("itemVariantId", "Item Variant Id"),
  uuid("locationId", "Location Id"),
];

export const purchaseOrders: EntityDefinition = {
  entityName: "purchaseOrder",
  entitySetName: "purchaseOrders",
  pageId: "PAG30066",
  apiBase: "standard",
  description:
    "Manages purchase order documents including vendor details, pricing, delivery, and status.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    date("orderDate", "Order Date"),
    date("postingDate", "Posting Date"),
    uuid("vendorId", "Vendor Id"),
    str("vendorNumber", "Vendor No."),
    ro(str("vendorName", "Vendor Name")),
    str("payToName", "Pay-to Name"),
    str("payToVendorNumber", "Pay-to Vendor No."),
    uuid("payToVendorId", "Pay-to Vendor Id"),
    str("shipToName", "Ship-to Name"),
    str("shipToContact", "Ship-to Contact"),
    str("buyFromAddressLine1", "Buy-from Address Line 1"),
    str("buyFromAddressLine2", "Buy-from Address Line 2"),
    str("buyFromCity", "Buy-from City"),
    str("buyFromCountry", "Buy-from Country/Region Code"),
    str("buyFromState", "Buy-from State"),
    str("buyFromPostCode", "Buy-from ZIP Code"),
    str("shipToAddressLine1", "Ship-to Address Line 1"),
    str("shipToAddressLine2", "Ship-to Address Line 2"),
    str("shipToCity", "Ship-to City"),
    str("shipToCountry", "Ship-to Country/Region Code"),
    str("shipToState", "Ship-to State"),
    str("shipToPostCode", "Ship-to ZIP Code"),
    str("payToAddressLine1", "Pay-to Address Line 1"),
    str("payToAddressLine2", "Pay-to Address Line 2"),
    str("payToCity", "Pay-to City"),
    str("payToCountry", "Pay-to Country/Region Code"),
    str("payToState", "Pay-to State"),
    str("payToPostCode", "Pay-to ZIP Code"),
    str("shortcutDimension1Code", "Shortcut Dimension 1 Code"),
    str("shortcutDimension2Code", "Shortcut Dimension 2 Code"),
    uuid("currencyId", "Currency Id"),
    str("currencyCode", "Currency Code"),
    bool("pricesIncludeTax", "Prices Include Tax"),
    uuid("paymentTermsId", "Payment Terms Id"),
    str("purchaser", "Purchaser"),
    date("requestedReceiptDate", "Requested Receipt Date"),
    ro(decimal("discountAmount", "Discount Amount")),
    ro(bool("discountAppliedBeforeTax", "Discount Applied Before Tax")),
    ro(decimal("totalAmountExcludingTax", "Total Amount Excluding Tax")),
    ro(decimal("totalTaxAmount", "Total Tax Amount")),
    ro(decimal("totalAmountIncludingTax", "Total Amount Including Tax")),
    ro(bool("fullyReceived", "Fully Received")),
    ro(str("status", "Status")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const purchaseOrderLines: EntityDefinition = {
  entityName: "purchaseOrderLine",
  entitySetName: "purchaseOrderLines",
  pageId: "PAG30067",
  apiBase: "standard",
  description: "Exposes purchase order line data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "purchaseOrders",
    parentKeyParam: "PurchaseOrder_id",
    parentDescription: "Parent purchase order identification.",
    parentListTool: "ListPurchaseOrders_PAG30066",
  },
  properties: purchaseLineProps,
};

export const purchaseInvoices: EntityDefinition = {
  entityName: "purchaseInvoice",
  entitySetName: "purchaseInvoices",
  pageId: "PAG30042",
  apiBase: "standard",
  description: "Exposes purchase invoice documents.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    date("invoiceDate", "Invoice Date"),
    date("dueDate", "Due Date"),
    date("postingDate", "Posting Date"),
    uuid("vendorId", "Vendor Id"),
    str("vendorNumber", "Vendor No."),
    ro(str("vendorName", "Vendor Name")),
    uuid("currencyId", "Currency Id"),
    str("currencyCode", "Currency Code"),
    uuid("paymentTermsId", "Payment Terms Id"),
    str("purchaser", "Purchaser"),
    ro(decimal("totalAmountExcludingTax", "Total Amount Excluding Tax")),
    ro(decimal("totalTaxAmount", "Total Tax Amount")),
    ro(decimal("totalAmountIncludingTax", "Total Amount Including Tax")),
    ro(str("status", "Status")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const purchaseInvoiceLines: EntityDefinition = {
  entityName: "purchaseInvoiceLine",
  entitySetName: "purchaseInvoiceLines",
  pageId: "PAG30047",
  apiBase: "standard",
  description: "Exposes purchase invoice line data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "purchaseInvoices",
    parentKeyParam: "PurchaseInvoice_id",
    parentDescription: "Parent purchase invoice identification.",
    parentListTool: "ListPurchaseInvoices_PAG30042",
  },
  properties: purchaseLineProps,
};

export const purchaseReceipts: EntityDefinition = {
  entityName: "purchaseReceipt",
  entitySetName: "purchaseReceipts",
  pageId: "PAG30064",
  apiBase: "standard",
  description: "Exposes posted purchase receipt header data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    date("orderDate", "Order Date"),
    date("postingDate", "Posting Date"),
    str("vendorNumber", "Vendor No."),
    ro(str("vendorName", "Vendor Name")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const purchaseReceiptLines: EntityDefinition = {
  entityName: "purchaseReceiptLine",
  entitySetName: "purchaseReceiptLines",
  pageId: "PAG30065",
  apiBase: "standard",
  description: "Exposes posted purchase receipt line data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "purchaseReceipts",
    parentKeyParam: "PurchaseReceipt_id",
    parentDescription: "Parent purchase receipt identification.",
    parentListTool: "ListPurchaseReceipts_PAG30064",
  },
  properties: [
    uuid("id", "Id"),
    uuid("documentId", "Document Id"),
    int32("sequence", "Sequence"),
    str("lineObjectNumber", "Line Object Number"),
    str("description", "Description"),
    str("unitOfMeasureCode", "Unit of Measure Code"),
    decimal("quantity", "Quantity"),
    date("expectedReceiptDate", "Expected Receipt Date"),
  ],
};

export const purchaseCreditMemos: EntityDefinition = {
  entityName: "purchaseCreditMemo",
  entitySetName: "purchaseCreditMemos",
  pageId: "PAG30083",
  apiBase: "standard",
  description: "Exposes purchase credit memo documents.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    date("creditMemoDate", "Credit Memo Date"),
    date("dueDate", "Due Date"),
    date("postingDate", "Posting Date"),
    uuid("vendorId", "Vendor Id"),
    str("vendorNumber", "Vendor No."),
    ro(str("vendorName", "Vendor Name")),
    uuid("currencyId", "Currency Id"),
    str("currencyCode", "Currency Code"),
    uuid("paymentTermsId", "Payment Terms Id"),
    str("purchaser", "Purchaser"),
    ro(decimal("totalAmountExcludingTax", "Total Amount Excluding Tax")),
    ro(decimal("totalTaxAmount", "Total Tax Amount")),
    ro(decimal("totalAmountIncludingTax", "Total Amount Including Tax")),
    ro(str("status", "Status")),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const purchaseCreditMemoLines: EntityDefinition = {
  entityName: "purchaseCreditMemoLine",
  entitySetName: "purchaseCreditMemoLines",
  pageId: "PAG30084",
  apiBase: "standard",
  description: "Exposes purchase credit memo line data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  subEntityOf: {
    parentEntitySetName: "purchaseCreditMemos",
    parentKeyParam: "PurchaseCreditMemo_id",
    parentDescription: "Parent purchase credit memo identification.",
    parentListTool: "ListPurchaseCreditMemos_PAG30083",
  },
  properties: purchaseLineProps,
};

export const applyVendorEntries: EntityDefinition = {
  entityName: "applyVendorEntry",
  entitySetName: "applyVendorEntries",
  pageId: "PAG30073",
  apiBase: "standard",
  description: "Exposes vendor ledger entries available for application.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    int32("entryNo", "Entry No."),
    str("vendorNo", "Vendor No."),
    date("postingDate", "Posting Date"),
    str("documentType", "Document Type"),
    str("documentNo", "Document No."),
    str("description", "Description"),
    decimal("remainingAmount", "Remaining Amount"),
    decimal("amount", "Amount"),
    date("dueDate", "Due Date"),
    str("currencyCode", "Currency Code"),
  ],
};

export const itemLedgerEntries: EntityDefinition = {
  entityName: "itemLedgerEntry",
  entitySetName: "itemLedgerEntries",
  pageId: "PAG30069",
  apiBase: "standard",
  description: "Exposes item ledger entries for inventory tracking.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    int32("entryNumber", "Entry Number"),
    str("itemNumber", "Item Number"),
    date("postingDate", "Posting Date"),
    str("entryType", "Entry Type"),
    str("documentNumber", "Document Number"),
    str("documentType", "Document Type"),
    str("description", "Description"),
    decimal("quantity", "Quantity"),
    decimal("remainingQuantity", "Remaining Quantity"),
    str("locationCode", "Location Code"),
    decimal("costAmountActual", "Cost Amount (Actual)"),
    decimal("salesAmountActual", "Sales Amount (Actual)"),
  ],
};

export const opportunities: EntityDefinition = {
  entityName: "opportunity",
  entitySetName: "opportunities",
  pageId: "PAG30070",
  apiBase: "standard",
  description: "Exposes CRM opportunity records.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("description", "Description"),
    str("contactNumber", "Contact Number"),
    str("contactName", "Contact Name"),
    str("contactCompanyName", "Contact Company Name"),
    str("salespersonCode", "Salesperson Code"),
    str("status", "Status"),
    date("closingDate", "Closing Date"),
    decimal("estimatedValue", "Estimated Value"),
    int32("probability", "Probability"),
  ],
};

export const fixedAssets: EntityDefinition = {
  entityName: "fixedAsset",
  entitySetName: "fixedAssets",
  pageId: "PAG30098",
  apiBase: "standard",
  description: "Exposes fixed asset master data.",
  keyStrategy: { kind: "uuid" },
  operations: listOnly,
  properties: [
    uuid("id", "Id"),
    str("number", "Number"),
    str("displayName", "Display Name"),
    str("fixedAssetLocationId", "Fixed Asset Location Id"),
    str("fixedAssetLocationCode", "Fixed Asset Location Code"),
    str("classCode", "Class Code"),
    str("subclassCode", "Subclass Code"),
    bool("blocked", "Blocked"),
    str("serialNumber", "Serial Number"),
    str("responsibleEmployee", "Responsible Employee"),
    ro(datetime("lastModifiedDateTime", "Last Modified Date-Time")),
  ],
};

export const purchasingEntities: EntityDefinition[] = [
  purchaseOrders,
  purchaseOrderLines,
  purchaseInvoices,
  purchaseInvoiceLines,
  purchaseReceipts,
  purchaseReceiptLines,
  purchaseCreditMemos,
  purchaseCreditMemoLines,
  applyVendorEntries,
  itemLedgerEntries,
  opportunities,
  fixedAssets,
];
